language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    - php: 5.3
      dist: precise
      env: INSTALL_APC="yes"
    - php: 5.3
      dist: precise
      env: INSTALL_APC="yes" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    # The new Trusty image has issues with running APC, do not enable it here
    - php: 5.4
      env: INSTALL_APC="no"
    - php: 5.5
      env: INSTALL_APCU="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
    - php: 7.1
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
    - php: 7.1
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes" COMPOSER_FLAGS=""
    - php: 7.2
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
    - php: 7.3
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
    - php: 7.4
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
    - php: nightly
      env: INSTALL_APCU="yes" INSTALL_MEMCACHED="yes" INSTALL_REDIS="yes"
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis-server

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS
  # Enable additional PHP extensions
  - if [ "$INSTALL_MEMCACHED" == "yes" ]; then phpenv config-add .travis/phpenv/memcached.ini; fi
  - if [ "$INSTALL_APC" == "yes" ]; then phpenv config-add .travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "5.*" ]; then printf "\n" | pecl install apcu-4.0.10 && phpenv config-add .travis/phpenv/apcu-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "7.*" ]; then printf "\n" | pecl install apcu-beta && phpenv config-add .travis/phpenv/apcu-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$INSTALL_REDIS" == "yes" ]; then phpenv config-add .travis/phpenv/redis.ini; fi

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=Joomla src/; fi;
